# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0fdd33b61ed268a078e0964b46cf97b2f1a60ffb42fcb655e8332ee08ec4e0e887d56623bf03284b216eef9ccc6f7f9e3034451cf7f239a8da4f373edb67e85

test:
  secret_key_base: ccaac69ee628f6d63e918555edec62fcca7f5876d9a67497f8eb5a9f622350d9a8755f1593a6a2dd872564265804cfa1f96c9ba32ecc67e96312a2d770c0d160

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
